services:
  - docker

language: minimal

os:
  - linux

#compiler:
#  - clang

install:
  - docker-compose build
  - docker-compose up 

script: 
  - docker-compose run ece566 bash ./travis-ci-test.sh

after_script:
  - docker-compose stop
  - docker-compose rm -f
